sudo: required
services:
  -docker

before_install:
  - docker build -t divij07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true divij07/react-test npm test

after_success:
  - docker build -t divij07/multi-client ./client
  - docker build -t divij07/multi-nginx ./nginx
  - docker build -t divij07/multi-server ./server
  - docker build -t divij07/multi-worker ./worker
  - echo "$Docker_Password" | docker login -u "$Docker_Id" --password-stdin
  - docker push divij07/multi-client
  - docker push divij07/multi-nginx
  - docker push divij07/multi-server
  - docker push divij07/multi-worker
